default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: api_dev
test:
  <<: *default
  database: api_test
production:
  <<: *default
  database: api
  username: api-username
  password: <%= ENV['RAILS_API_TEMPLATE_DATABASE_PASSWORD'] %>
